#! /bin/sh

### BEGIN INIT INFO
# Provides:          lively-terminal
# Required-Start:    
# Required-Stop:
# X-Start-Before:    
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Lively4 xterm.js terminal login server
# Description: start Lively4 xterm.js with login server
### END INIT INFO

. /lib/lsb/init-functions


case "$1" in
  start)
	# make sure privileges don't persist across reboots
    echo "start Lively4 terminal server"
    cd /home/jens/lively4/xterm.js/demo; 
    /home/jens/.nvm/versions/node/v10.14.1/bin/node loginserver.js &
	;;
  stop|reload|restart|force-reload|status)
    killall loginserver.js
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
